export default {
  fonts: {
    body: "roboto, system-ui, sans-serif",
    heading: "roboto, system-ui, sans-serif",
    monospace: "Menlo, monospace",
  },
  colors: {
    orange: "hsl(16, 88%, 55%)",
    blue: "hsl(212, 74%, 34%)",
    grey: "hsl(201, 23%, 34%)",
    lightGrey: "hsl(203, 15%, 47%)",
    backGroundGrey: "hsl(0, 0%, 96%)",
    text: "hsl(0, 0%, 28%)",
    lightBlue: "hsl(212, 74%,50%)",
    faintBlue: "hsl(220, 88%, 88%)",
    darkBlue: "hsl(212, 88%, 23%)",
    faintOrange: "hsl(36, 100%, 88%)",
    dGrey: "rgb(236, 236, 236)",
  },
  fontWeights: {
    thin: 100,
    light: 200,
    body: 400,
    heading: 700,
    bold: 700,
  },
  styles: {
    h2: {
      fontSize: [4, 5],
      fontFamily: "body",
      fontWeight: "bold",
      color: "darkBlue",

      mt: 3,
      mb: 0,
      mx: [4, 5],
      bg: "white",
    },
    h3: {
      fontSize: 1,
      fontFamily: "body",
      fontWeight: "bold",
      color: "grey",
      mt: 3,
      mb: 0,
      mx: [4, 5],
    },
    p: {
      fontSize: [1, 2, 3],
      fontFamily: "body",
      fontWeight: "body",
      color: "grey",
      mt: [3, 4],
      mx: [4, 5],
      mb: 2,
    },
    ul: {
      mx: [4, 5],
      mt: 1,
      mb: 3,
      p: 0,
      fontSize: [1, 2, 3],
      fontFamily: "body",
      fontWeight: "body",
      color: "grey",
    },
    li: {
      mx: 3,
      mb: 1,
    },
  },
}
